---
- name: Install iptables packages
  apt:
    name:
      - iptables
      - iptables-persistent
    state: present
    update_cache: yes
  when: firewall_backend == 'iptables'

- name: Install nftables packages
  apt:
    name:
      - nftables
    state: present
    update_cache: yes
  when: firewall_backend == 'nftables'

- name: Install HA packages
  apt:
    name:
      - keepalived
      - conntrackd
      - auditd
    state: present
    update_cache: yes 