---
- name: Include iptables rule sets
  include_vars:
    file: "{{ item }}"
  loop:
    - "{{ role_path }}/vars/iptables_rules/input.yml"
    - "{{ role_path }}/vars/iptables_rules/output.yml"
    - "{{ role_path }}/vars/iptables_rules/forward.yml"
    - "{{ role_path }}/vars/iptables_rules/nat_prerouting.yml"
    - "{{ role_path }}/vars/iptables_rules/nat_postrouting.yml"

- name: Combine all iptables rules
  set_fact:
    iptables_rules: >-
      {{ (input_rules | map('combine', {'chain': 'INPUT'}) | list)
         + (output_rules | map('combine', {'chain': 'OUTPUT'}) | list)
         + (forward_rules | map('combine', {'chain': 'FORWARD'}) | list)
         + (nat_prerouting_rules | map('combine', {'chain': 'PREROUTING'}) | list)
         + (nat_postrouting_rules | map('combine', {'chain': 'POSTROUTING'}) | list) }} 