---
# Handlers for iptables-ha role

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted

- name: restart conntrackd
  systemd:
    name: conntrackd
    state: restarted

- name: restart auditd
  systemd:
    name: auditd
    state: restarted

- name: restart nftables
  systemd:
    name: nftables
    state: restarted

- name: reload nftables
  systemd:
    name: nftables
    state: reloaded 